#ifndef _PINS_H_
#define _PINS_H_
#include "stm32f103c8t6.h"
/*
 * This is a generated file. Do not modify directly!
 * -------------------------------------------------
 * 
 * This file contains macros for more convenient register access.
 * 
 * - PIN_GPIO_CRXx
 *    CRL or CRH for pin x
 * 
 * - PIN_GPIO_CRX_CNFx
 *    The GPIO CRL/CRH CNF bit for pin x
 * 
 * - PIN_GPIO_CRX_MODE
 *    The GPIO CRL/CRH MODE bit for pin x
 * 
 * "Function"-like macros for convenience:
 * 
 * - pin_gpio_set_high(port, idx)
 *    Sets the GPIO pin to HIGH.
 * 
 * - pin_gpio_set_low(port, idx)
 *    Sets the GPIO pin to LOW.
 * 
 */

// GPIO set high/low
#define pin_gpio_set_high(port, idx) GPIO##port->BSRR = GPIO_BSRR_BS##idx
#define pin_gpio_set_low(port, idx) GPIO##port->BSRR = GPIO_BSRR_BR##idx

// CRL vs. CRH for each pin number
#define PIN_GPIO_CRX0 CRL
#define PIN_GPIO_CRX1 CRL
#define PIN_GPIO_CRX2 CRL
#define PIN_GPIO_CRX3 CRL
#define PIN_GPIO_CRX4 CRL
#define PIN_GPIO_CRX5 CRL
#define PIN_GPIO_CRX6 CRL
#define PIN_GPIO_CRX7 CRL
#define PIN_GPIO_CRX8 CRH
#define PIN_GPIO_CRX9 CRH
#define PIN_GPIO_CRX10 CRH
#define PIN_GPIO_CRX11 CRH
#define PIN_GPIO_CRX12 CRH
#define PIN_GPIO_CRX13 CRH
#define PIN_GPIO_CRX14 CRH
#define PIN_GPIO_CRX15 CRH

// GPIO_CRx_CNF
#define PIN_GPIO_CRX_CNF0 GPIO_CRL_CNF0
#define PIN_GPIO_CRX_CNF0_0 GPIO_CRL_CNF0_0
#define PIN_GPIO_CRX_CNF0_1 GPIO_CRL_CNF0_1
#define PIN_GPIO_CRX_CNF1 GPIO_CRL_CNF1
#define PIN_GPIO_CRX_CNF1_0 GPIO_CRL_CNF1_0
#define PIN_GPIO_CRX_CNF1_1 GPIO_CRL_CNF1_1
#define PIN_GPIO_CRX_CNF2 GPIO_CRL_CNF2
#define PIN_GPIO_CRX_CNF2_0 GPIO_CRL_CNF2_0
#define PIN_GPIO_CRX_CNF2_1 GPIO_CRL_CNF2_1
#define PIN_GPIO_CRX_CNF3 GPIO_CRL_CNF3
#define PIN_GPIO_CRX_CNF3_0 GPIO_CRL_CNF3_0
#define PIN_GPIO_CRX_CNF3_1 GPIO_CRL_CNF3_1
#define PIN_GPIO_CRX_CNF4 GPIO_CRL_CNF4
#define PIN_GPIO_CRX_CNF4_0 GPIO_CRL_CNF4_0
#define PIN_GPIO_CRX_CNF4_1 GPIO_CRL_CNF4_1
#define PIN_GPIO_CRX_CNF5 GPIO_CRL_CNF5
#define PIN_GPIO_CRX_CNF5_0 GPIO_CRL_CNF5_0
#define PIN_GPIO_CRX_CNF5_1 GPIO_CRL_CNF5_1
#define PIN_GPIO_CRX_CNF6 GPIO_CRL_CNF6
#define PIN_GPIO_CRX_CNF6_0 GPIO_CRL_CNF6_0
#define PIN_GPIO_CRX_CNF6_1 GPIO_CRL_CNF6_1
#define PIN_GPIO_CRX_CNF7 GPIO_CRL_CNF7
#define PIN_GPIO_CRX_CNF7_0 GPIO_CRL_CNF7_0
#define PIN_GPIO_CRX_CNF7_1 GPIO_CRL_CNF7_1
#define PIN_GPIO_CRX_CNF8 GPIO_CRH_CNF8
#define PIN_GPIO_CRX_CNF8_0 GPIO_CRH_CNF8_0
#define PIN_GPIO_CRX_CNF8_1 GPIO_CRH_CNF8_1
#define PIN_GPIO_CRX_CNF9 GPIO_CRH_CNF9
#define PIN_GPIO_CRX_CNF9_0 GPIO_CRH_CNF9_0
#define PIN_GPIO_CRX_CNF9_1 GPIO_CRH_CNF9_1
#define PIN_GPIO_CRX_CNF10 GPIO_CRH_CNF10
#define PIN_GPIO_CRX_CNF10_0 GPIO_CRH_CNF10_0
#define PIN_GPIO_CRX_CNF10_1 GPIO_CRH_CNF10_1
#define PIN_GPIO_CRX_CNF11 GPIO_CRH_CNF11
#define PIN_GPIO_CRX_CNF11_0 GPIO_CRH_CNF11_0
#define PIN_GPIO_CRX_CNF11_1 GPIO_CRH_CNF11_1
#define PIN_GPIO_CRX_CNF12 GPIO_CRH_CNF12
#define PIN_GPIO_CRX_CNF12_0 GPIO_CRH_CNF12_0
#define PIN_GPIO_CRX_CNF12_1 GPIO_CRH_CNF12_1
#define PIN_GPIO_CRX_CNF13 GPIO_CRH_CNF13
#define PIN_GPIO_CRX_CNF13_0 GPIO_CRH_CNF13_0
#define PIN_GPIO_CRX_CNF13_1 GPIO_CRH_CNF13_1
#define PIN_GPIO_CRX_CNF14 GPIO_CRH_CNF14
#define PIN_GPIO_CRX_CNF14_0 GPIO_CRH_CNF14_0
#define PIN_GPIO_CRX_CNF14_1 GPIO_CRH_CNF14_1
#define PIN_GPIO_CRX_CNF15 GPIO_CRH_CNF15
#define PIN_GPIO_CRX_CNF15_0 GPIO_CRH_CNF15_0
#define PIN_GPIO_CRX_CNF15_1 GPIO_CRH_CNF15_1

// GPIO_CRx_MODE
#define PIN_GPIO_CRX_MODE0 GPIO_CRL_MODE0
#define PIN_GPIO_CRX_MODE0_0 GPIO_CRL_MODE0_0
#define PIN_GPIO_CRX_MODE0_1 GPIO_CRL_MODE0_1
#define PIN_GPIO_CRX_MODE1 GPIO_CRL_MODE1
#define PIN_GPIO_CRX_MODE1_0 GPIO_CRL_MODE1_0
#define PIN_GPIO_CRX_MODE1_1 GPIO_CRL_MODE1_1
#define PIN_GPIO_CRX_MODE2 GPIO_CRL_MODE2
#define PIN_GPIO_CRX_MODE2_0 GPIO_CRL_MODE2_0
#define PIN_GPIO_CRX_MODE2_1 GPIO_CRL_MODE2_1
#define PIN_GPIO_CRX_MODE3 GPIO_CRL_MODE3
#define PIN_GPIO_CRX_MODE3_0 GPIO_CRL_MODE3_0
#define PIN_GPIO_CRX_MODE3_1 GPIO_CRL_MODE3_1
#define PIN_GPIO_CRX_MODE4 GPIO_CRL_MODE4
#define PIN_GPIO_CRX_MODE4_0 GPIO_CRL_MODE4_0
#define PIN_GPIO_CRX_MODE4_1 GPIO_CRL_MODE4_1
#define PIN_GPIO_CRX_MODE5 GPIO_CRL_MODE5
#define PIN_GPIO_CRX_MODE5_0 GPIO_CRL_MODE5_0
#define PIN_GPIO_CRX_MODE5_1 GPIO_CRL_MODE5_1
#define PIN_GPIO_CRX_MODE6 GPIO_CRL_MODE6
#define PIN_GPIO_CRX_MODE6_0 GPIO_CRL_MODE6_0
#define PIN_GPIO_CRX_MODE6_1 GPIO_CRL_MODE6_1
#define PIN_GPIO_CRX_MODE7 GPIO_CRL_MODE7
#define PIN_GPIO_CRX_MODE7_0 GPIO_CRL_MODE7_0
#define PIN_GPIO_CRX_MODE7_1 GPIO_CRL_MODE7_1
#define PIN_GPIO_CRX_MODE8 GPIO_CRH_MODE8
#define PIN_GPIO_CRX_MODE8_0 GPIO_CRH_MODE8_0
#define PIN_GPIO_CRX_MODE8_1 GPIO_CRH_MODE8_1
#define PIN_GPIO_CRX_MODE9 GPIO_CRH_MODE9
#define PIN_GPIO_CRX_MODE9_0 GPIO_CRH_MODE9_0
#define PIN_GPIO_CRX_MODE9_1 GPIO_CRH_MODE9_1
#define PIN_GPIO_CRX_MODE10 GPIO_CRH_MODE10
#define PIN_GPIO_CRX_MODE10_0 GPIO_CRH_MODE10_0
#define PIN_GPIO_CRX_MODE10_1 GPIO_CRH_MODE10_1
#define PIN_GPIO_CRX_MODE11 GPIO_CRH_MODE11
#define PIN_GPIO_CRX_MODE11_0 GPIO_CRH_MODE11_0
#define PIN_GPIO_CRX_MODE11_1 GPIO_CRH_MODE11_1
#define PIN_GPIO_CRX_MODE12 GPIO_CRH_MODE12
#define PIN_GPIO_CRX_MODE12_0 GPIO_CRH_MODE12_0
#define PIN_GPIO_CRX_MODE12_1 GPIO_CRH_MODE12_1
#define PIN_GPIO_CRX_MODE13 GPIO_CRH_MODE13
#define PIN_GPIO_CRX_MODE13_0 GPIO_CRH_MODE13_0
#define PIN_GPIO_CRX_MODE13_1 GPIO_CRH_MODE13_1
#define PIN_GPIO_CRX_MODE14 GPIO_CRH_MODE14
#define PIN_GPIO_CRX_MODE14_0 GPIO_CRH_MODE14_0
#define PIN_GPIO_CRX_MODE14_1 GPIO_CRH_MODE14_1
#define PIN_GPIO_CRX_MODE15 GPIO_CRH_MODE15
#define PIN_GPIO_CRX_MODE15_0 GPIO_CRH_MODE15_0
#define PIN_GPIO_CRX_MODE15_1 GPIO_CRH_MODE15_1

// Pin output configuration / setup
#define pin_set_output_50mhz(port, idx) GPIO##port->PIN_GPIO_CRX##idx = (GPIO##port->PIN_GPIO_CRX##idx & ~( PIN_GPIO_CRX_CNF##idx  | PIN_GPIO_CRX_MODE##idx )) | (PIN_GPIO_CRX_MODE##idx##_1 | PIN_GPIO_CRX_MODE##idx##_0)
#define pin_set_output_50mhz_alt(port, idx) GPIO##port->PIN_GPIO_CRX##idx = (GPIO##port->PIN_GPIO_CRX##idx & ~( PIN_GPIO_CRX_CNF##idx  | PIN_GPIO_CRX_MODE##idx )) | (PIN_GPIO_CRX_MODE##idx##_1 | PIN_GPIO_CRX_MODE##idx##_0 | PIN_GPIO_CRX_CNF##idx##_1)
#endif
